[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "whss-sampler"
version = "0.1.0"
authors = [
  { name="Dharmik Patel" },
]
description = "Warped Hybrid Slice Sampling (WHSS)"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "numba",
    "matplotlib",
    "tqdm"
]

[project.urls]
"Homepage" = "https://github.com/LeviTheScout/whss-sampler"
